### ISSUE TITLE
Fails to parse an erb multiline comment with quotes inside

### ISSUE THREAD

**Issue by rdimartino** [adamzapasnik/prettier-plugin-erb#18]
`template_with_comment.html.erb`:
```
<%# This is a 'quote' inside a
 multiline comment-%>
<h1>This file fails to parse</h1>
```

Attempting to format:

```
❯ yarn prettier --write template_with_comment.html.erb
yarn run v1.22.10
$ /Users/robert.dimartino/repro/node_modules/.bin/prettier --write template_with_comment.html.erb
template_with_comment.html.erbError: syntax error, unexpected local variable or method, expecting end-of-input
> 1 |  This is a 'quote' inside a
    |                         ^
  2 |  multiline comment
    at parseSync (/Users/robert.dimartino/repro/node_modules/@prettier/plugin-ruby/src/parser/parseSync.js:32:19)
    at Object.parse (/Users/robert.dimartino/repro/node_modules/@prettier/plugin-ruby/src/ruby/parser.js:8:10)
    at Object.parse (/Users/robert.dimartino/repro/node_modules/prettier/index.js:13625:19)
    at coreFormat (/Users/robert.dimartino/repro/node_modules/prettier/index.js:14899:14)
    at format (/Users/robert.dimartino/repro/node_modules/prettier/index.js:15131:14)
    at /Users/robert.dimartino/repro/node_modules/prettier/index.js:57542:12
    at format (/Users/robert.dimartino/repro/node_modules/prettier/index.js:57562:12)
    at /Users/robert.dimartino/repro/node_modules/prettier-plugin-erb/lib/formatter.js:16:37
    at Array.map (<anonymous>)
    at formatMultilineExpressions (/Users/robert.dimartino/repro/node_modules/prettier-plugin-erb/lib/formatter.js:7:6) {
  loc: { start: { line: 1, column: 25 } },
  codeFrame: "\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 1 | \x1B[39m \x1B[33mThis\x1B[39m is a \x1B[32m'quote'\x1B[39m inside a\x1B[0m\n" +
    '\x1B[0m \x1B[90m   | \x1B[39m                        \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 2 | \x1B[39m multiline comment\x1B[0m'
}
```

It works correctly if there are no quotes (single or double) in the multi-line comment and it works with the quotes if the tag is on one line. Not sure if there are other characters that cause syntax errors.

We encountered this error from our default kaminari templates: https://github.com/kaminari/kaminari/blob/master/kaminari-core/app/views/kaminari/_first_page.html.erb

**Comment by rdimartino** [comment]
Duplicate of #4
