### ISSUE TITLE
Formatter Chokes on Conditional Tags

### ISSUE THREAD

**Issue by wkirby** [adamzapasnik/prettier-plugin-erb#3]
We have an (admittedly weird) pattern in some of our ERB files. The parser chokes  on this, where we are conditionally adding opening and closing tags.

```erb
<% token ||= false %>
<% value ||= nil %>

<div>
  <% if token && value.present? %>
    <span class="token">
  <% end %>

  <%= value || yield %>

  <% if token && value.present? %>
    </span>
  <% end %>
</div>
```

I can rewrite this file to pass the parser, but this seems like it shouldn't blow up. Error is here:

```
app/views/shared/partials/_panel_card.html.erbSyntaxError: Unexpected closing tag "eext8". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (14:4)
  12 |
  13 |     <span class="token">
> 14 |    </eext8>
     |    ^^^^^^^^
  15 |
  16 |    <eext9 />
  17 |
    at vt (/app/node_modules/prettier/parser-html.js:41:48413)
    at Mn (/app/node_modules/prettier/parser-html.js:113:2409)
    at Un (/app/node_modules/prettier/parser-html.js:113:4175)
    at Object.parse (/app/node_modules/prettier/parser-html.js:113:4895)
    at Object.parse (/app/node_modules/prettier/index.js:13625:19)
    at textToDoc (/app/node_modules/prettier/index.js:14560:25)
    at /app/node_modules/prettier/index.js:14545:95
    at embed (/app/node_modules/prettier-plugin-erb/lib/printers.js:17:19)
    at Object.embed (/app/node_modules/prettier-plugin-erb/lib/printers.js:28:16)
    at Object.printSubtree (/app/node_modules/prettier/index.js:14545:28) {
  loc: { start: { line: 14, column: 4 }, end: { line: 14, column: 12 } },
  codeFrame: '\u001b[0m \u001b[90m 12 | \u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 13 | \u001b[39m    \u001b[33m<\u001b[39m\u001b[33mspan\u001b[39m \u001b[36mclass\u001b[39m\u001b[33m=\u001b[39m\u001b[32m"token"\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n' +
    '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 14 | \u001b[39m   \u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33meext8\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m    | \u001b[39m   \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 15 | \u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 16 | \u001b[39m   \u001b[33m<\u001b[39m\u001b[33meext9\u001b[39m \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m \u001b[0m\n' +
    '\u001b[0m \u001b[90m 17 | \u001b[39m\u001b[0m'
}
```

**Comment by wkirby** [comment]
I've rewritten it, but the final HTML output of the ERB is totally valid; we're conditionally wrapping the `<%= value %>` with a `<span>` element. I'm not sure at what stage the `<eext8>` tag gets added, but that's where it's breaking — the `<% if %>` and `<% end %>` tags are being turned into pseudo HTML elements, instead of being dropped for validating the HTML.
