### ISSUE TITLE
Formatter chokes on Administrate generated templates

### ISSUE THREAD

**Issue by wkirby** [adamzapasnik/prettier-plugin-erb#4]
We are using administrate for an admin panel, and have used its built in generators to customize the ERB templates. Almost all of these templates produce some version of the following error:

```
app/views/admin/application/_flashes.html.erbError: @prettier/plugin-ruby encountered an error when attempting to parse the ruby source. This usually means there was a syntax error in the file in question. You can verify by running `ruby -i [path/to/file]`.
    at parseSync (/Users/wyatt/Dev/app/node_modules/@prettier/plugin-ruby/src/parser/parseSync.js:23:11)
    at Object.parse (/Users/wyatt/Dev/app/node_modules/@prettier/plugin-ruby/src/ruby/parser.js:8:10)
    at Object.parse (/Users/wyatt/Dev/app/node_modules/prettier/index.js:13625:19)
    at coreFormat (/Users/wyatt/Dev/app/node_modules/prettier/index.js:14899:14)
    at format (/Users/wyatt/Dev/app/node_modules/prettier/index.js:15131:14)
    at /Users/wyatt/Dev/app/node_modules/prettier/index.js:57542:12
    at format (/Users/wyatt/Dev/app/node_modules/prettier/index.js:57562:12)
    at /Users/wyatt/Dev/app/node_modules/prettier-plugin-erb/lib/formatter.js:16:37
    at Array.map (<anonymous>)
    at formatMultilineExpressions (/Users/wyatt/Dev/clients/cmt/provider_portal/node_modules/prettier-plugin-erb/lib/formatter.js:7:6)
```

The underlying template file is very simple:

```erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <% if value.respond_to? :html_safe %>
        <div class="alert alert-<%= key %>"><%= value.html_safe %></div>
      <% end %>
    <% end -%>
  </div>
<% end %>
```

**Comment by wkirby** [comment]
It turns out this was really quick to track down. Any multi-line ERB comment blows up. I believe that `prettier-plugin-erb` is passing the multiline ERB statement on to the ruby parser, but because it's invalid Ruby (obviously, it's a comment), it is breaking.

**Comment by adamzapasnik** [comment]
Thanks for the issue. Good catch! I will figure out some fix this weekend. You can add the file to .prettierignore for now.

**Comment by kieranklaassen** [comment]
Basically all `<%#` tags crash it.
